# Generated by Django 4.1.4 on 2024-04-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
