# Generated by Django 4.1.4 on 2024-04-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_access_token_user_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='escrow_fund',
            field=models.FloatField(default=0.0),
        ),
    ]
