# Generated by Django 4.1.4 on 2024-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_escrow_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeotp',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='onetimeotp',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
