# Generated by Django 4.1.4 on 2024-04-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_onetimeotp_code_alter_onetimeotp_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
