# Generated by Django 4.1.4 on 2024-04-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_tier',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
