# Generated by Django 4.2.13 on 2024-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_account_number_alter_user_kyc_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
