# Generated by Django 4.2.13 on 2024-11-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default='', max_length=100)),
                ('account_id', models.CharField(default='', max_length=100)),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('card_number', models.CharField(max_length=160)),
                ('cvv', models.CharField(max_length=40)),
                ('expiry_month', models.CharField(max_length=20)),
                ('expiry_year', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pin', models.CharField(default='', max_length=20)),
                ('currency', models.CharField(default='', max_length=10)),
                ('tx_ref', models.CharField(max_length=50)),
                ('linked', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('card_type', models.CharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.IntegerField(default=0)),
                ('sender_by', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='', max_length=100)),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('escrow_description', models.CharField(default='', max_length=255)),
                ('escrow_name', models.CharField(default='', max_length=255)),
                ('escrow_Status', models.CharField(default='', max_length=100)),
                ('payment_type', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
                ('role_paying', models.CharField(default='', max_length=100)),
                ('estimated_days', models.CharField(default='', max_length=100)),
                ('number_milestone', models.CharField(default='', max_length=100)),
                ('milestone', models.CharField(default='', max_length=100)),
                ('reference', models.CharField(default='', max_length=100)),
                ('sender_name', models.CharField(default='', max_length=80)),
                ('receiver_email', models.EmailField(blank=True, default='', max_length=100)),
                ('receiver_id', models.IntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('link_url', models.URLField(default='')),
                ('make_payment', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('answered', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_fee', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('dispute', models.CharField(default='', max_length=80)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Escrow',
                'verbose_name_plural': 'Escrow',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', max_length=100)),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('topic', models.CharField(default='', max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='', max_length=15)),
                ('amount', models.IntegerField(default=0)),
                ('operator_id', models.CharField(default='', max_length=20)),
                ('product_id', models.CharField(default='ONCE', max_length=10)),
                ('meter_type', models.CharField(default='', max_length=50)),
                ('device_number', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_msisdn', models.DateTimeField(auto_now_add=True)),
                ('bill_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='', max_length=100)),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('organization_id', models.CharField(default='', max_length=24)),
                ('environment', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('link_id', models.CharField(default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='', max_length=10)),
                ('link_url', models.URLField(default='')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payment Link',
                'verbose_name_plural': 'Payment Links',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_account_number', models.CharField(default='', max_length=20)),
                ('bank', models.CharField(default='', max_length=200)),
                ('bank_code', models.CharField(default='', max_length=100)),
                ('reference', models.CharField(default='', max_length=100)),
                ('account_id', models.CharField(default='', max_length=100)),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('account_number', models.CharField(default='', max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('narration', models.TextField(default='')),
                ('transaction_fee', models.IntegerField(default=0)),
                ('user_balance', models.IntegerField(default=0)),
                ('receiver_name', models.CharField(default='', max_length=100)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('credit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.IntegerField(default=0, max_length=200)),
                ('narration', models.CharField(default='')),
                ('amount', models.IntegerField(default=0)),
                ('payment_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='transactions.paymentlink')),
            ],
            options={
                'verbose_name': 'Payment Detail',
                'verbose_name_plural': 'Payment Details',
            },
        ),
    ]
