# Generated by Django 4.1.4 on 2024-04-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default='', max_length=100)),
                ('account_id', models.CharField(default='', max_length=100)),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=10)),
                ('balance', models.FloatField(default=0.0)),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('pin', models.IntegerField(default=0)),
                ('currency', models.CharField(default='', max_length=10)),
                ('tx_ref', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('topic', models.CharField(default='', max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='', max_length=15)),
                ('amount', models.IntegerField(default=0)),
                ('operator_id', models.CharField(default='', max_length=20)),
                ('product_id', models.CharField(default='ONCE', max_length=10)),
                ('meter_type', models.CharField(default='', max_length=50)),
                ('device_number', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_msisdn', models.DateTimeField(auto_now_add=True)),
                ('bill_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('account_id', models.CharField(default='', max_length=100)),
                ('customer_id', models.CharField(default='', max_length=100)),
                ('organization_id', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('environment', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('link_id', models.CharField(max_length=8)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('link_url', models.URLField()),
                ('amount', models.IntegerField()),
                ('is_disabled', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Payment Link',
                'verbose_name_plural': 'Payment Links',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_account_number', models.CharField(default='', max_length=20)),
                ('bank', models.CharField(default='', max_length=20)),
                ('bank_code', models.CharField(default='', max_length=10)),
                ('reference', models.CharField(default='', max_length=100)),
                ('account_id', models.CharField(default='', max_length=100)),
                ('account_number', models.CharField(default='', max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('narration', models.TextField(default='')),
                ('transaction_fee', models.IntegerField(default=0)),
                ('credit', models.BooleanField(default=False)),
            ],
        ),
    ]
