# Generated by Django 4.1.4 on 2024-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentlink',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='link_url',
            field=models.URLField(default=''),
        ),
    ]
