# Generated by Django 4.1.4 on 2024-04-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_paymentlink_country_alter_paymentlink_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
