# Generated by Django 4.1.4 on 2024-04-11 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
