# Generated by Django 4.1.4 on 2024-04-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank',
            field=models.CharField(default='', max_length=200),
        ),
    ]
