# Generated by Django 4.1.4 on 2024-04-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
