# Generated by Django 4.1.4 on 2024-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_card_brand_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
