# Generated by Django 4.1.4 on 2024-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_paymentlink_created_at_paymentlink_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.CharField(default='', max_length=20),
        ),
    ]
