# Generated by Django 4.2.13 on 2024-05-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_escrow_reference_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='escrow_id',
            field=models.IntegerField(default=0),
        ),
    ]
