# Generated by Django 4.2.13 on 2024-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_escrow_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_by',
            field=models.IntegerField(default=0),
        ),
    ]
