# Generated by Django 4.2.13 on 2024-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_chatmessage_sender_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='receiver_id',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
