# Generated by Django 4.2.13 on 2024-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_escrow_receiver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
