# Generated by Django 4.2.13 on 2024-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_escrow_make_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='receiver_id',
            field=models.IntegerField(default=0),
        ),
    ]
